2pisoftware/cmfive-boilerplate

.gitignore, composer.json, composer.lock
=> Added composer

.build/Dockerfile
Removed the Apache Service from the Dockerfile
=> Dockerfile Update

.htaccess
- Fixed a bug causing Apache2 to block access to the root path.
=> fix: htaccess root path

.htaccess
- Fixed a bug with serving HTML files in Apache2.
=> fix: htaccess fix

cmfiveTests.php
Cleaned up the CLI output for unit tests to only show when a test fails. This will help keep the output small when we have more unit tests. Also the output colour of a failed unit test is red.
- Cleaned up the CLI output to only show when there is an error.
- Made the output of an error red.
=> feat: cleaner cli output

.github/pull_request_template.md
- Added the same pull request template that is being used in core.
=>  feat: pull request template

.github/pull_request_template.md, .github/semantic.yml, .github/workflows/ci.yml
- Added semantic pull requests config file.
- Renamed main.yml to ci.yml.
- Cleaned up CI action.
- Removed PHPCS checkbox in PR template as the CI action automatically checks this now.
=> feat: semantic pull requests

.github/pull_request_template.md, .github/semantic.yml, .github/workflows/ci.yml
- Added semantic pull requests config file.
- Added the same pull request template that is being used in core.
- Renamed main.yml to ci.yml.
- Cleaned up CI action.
- Cleaned up the CLI output to only show when there is an error.
- Made the CLI output of an error red.
=> feat: develop

.github/pull_request_template.md, .github/workflows/ci.yml
- Updated CI action for PHP 7.4.
- Updated pull request template.
=> fix: updated ci action

config.php.example
- Cleaned up the example config to be PSR2 compliant.
=> fix: config example cleanup

.htaccess
=> fix: adding svg to .htaccess

appspec.yml
- Fixed a typo in appspec.yml.
=> fix: appspec typo

.codepipeline/test_agent/Dockerfile, .codepipeline/test_agent/configs/test_agent-config.php, .codepipeline/test_agent/start.sh, test_agent-compose.yml
Config Patches to master to allow CRM CI tests against 7.4
=> Feature/outboard test config for7.4

.build/environment/dev/configs/docker/Dockerfile.template, .build/environment/prod/configs/docker/Dockerfile.template, cmfive.php
Resolving merge conflicts proposed by 61
https://github.com/2pisoftware/cmfive-boilerplate/pull/61
=> Fix: resolve from master for merging

.codepipeline/local-dev/configs/nginx/default.conf, .codepipeline/local-dev/local-dev-config.php, .codepipeline/local-dev/start.sh, .codepipeline/test_agent/configs/test_agent-config.php, .github/workflows/ci.yml, .gitignore, README.md, cmfiveTests.php, docker-compose.yml, test/.install/install.sh, test/Codeception/tests/boilerplate/CmfiveUI.php, test/Codeception/tests/boilerplate/acceptance/helpers/CmfiveSite.php, test_agent-compose.yml
Upgrade test setup for PHP8.1 against Codeception5
=> Feature: work to codeception5

.codepipeline/test_agent/Dockerfile, test_agent-compose.yml
=> Fix test issues

docker-compose.yml
=> Change working dir to avoid symlink

docker-compose.yml
Improvements to healthchecks which may solve a condition where the compiler wasnt finished.
Tested locally.
=> Improve healthchecks

test/playwright/cmfive.utils.ts
=> fix: playwright test is bs5 fix

test/playwright/package-lock.json, test/playwright/package.json
=> Remove unused glob-fs test dependency

.github/dependabot.yml, .github/workflows/ci.yml
Sync dependabot and update CI
refs:
issues:
=> chore(ci): Sync dependabot and update CI

test/playwright/cmfive.utils.ts
Improvements to existing playwright utility functions to be more reliable
- Login playwright utility function now ensures home page reached before resolving
- navigation utility function uses a more specific locator
refs:
issues:
=> Improvements to playwright login utility function

.github/workflows/docker-image.yml
=> Opencontainers labels

Dockerfile
Fixes currency format causing a test to fail. See:
https://github.com/2pisoftware/cmfive-core/actions/runs/8013419361/job/21890422431#step:13:67
Adds a new package to the base image for cmfive.
=> Fixes currency format

.codepipeline/docker/Dockerfile, .codepipeline/docker/README.md, .codepipeline/docker/configs/supervisord/supervisord.conf, .codepipeline/docker/setup.sh, docker-compose.yml, index.php
- Configurable core branch
- Improved container logs, and setup script
- Better docker documentation
- Other minor tweaks
=> Docker tweaks

.codepipeline/docker/configs/fpm/php.ini, .codepipeline/docker/configs/nginx/nginx.conf, Dockerfile
Fixes uploads not working in dev environments
=> fix: Uploads not working in dev environments

.codepipeline/docker/setup.sh
Make built-in admin user lowercase to match tests
=> Fix: Make built-in admin user lowercase to match tests

.github/workflows/docker-image.yml
Adds ARM builds to docker build
=> feat: Arm build

.codepipeline/docker/cmfive_dev_tools.sh, .codepipeline/docker/install_dev_tools.sh, .codepipeline/local-dev/50_xdebug.ini, .gitignore, Dockerfile, README.md, dev.dockerfile, docker-compose.yml
=> feat: Add xdebug support

.codepipeline/local-dev/50_xdebug.ini
=> Feat: Remove xdebug config

.codepipeline/docker/setup.sh, .codepipeline/ec2/after-install.sh, .codepipeline/ec2/application-start.sh, .codepipeline/ec2/application-stop.sh, .codepipeline/ec2/before-install.sh, Dockerfile, README.md, cmfive.php, cmfiveTests.php, cmfiveToolsDB.php
=> Update EC2 scripts for docker deployment

Dockerfile
Add cache invalidation so that the core is always up to date
=> fix: Cache invalidation for core

.codepipeline/docker/setup.sh, .github/workflows/docker-image.yml, .github/workflows/playwright.yml, Dockerfile
* Playwright testing
* Change name
* Change job trigger
* Fix core checkout
* Require image to be built before calling playwright
* Add core metadata (#172)
* Metadata
* Revert field overrides
* Install develop core for other branches
* Add build arg to x64 image
* Only trigger playwright on PR's
refs:
issues:
=> Master -> Develop

.codepipeline/docker/configs/nginx/default.conf
=> Chore: Bring docker container nginx config to parity with CDK
