test/.install/install.sh

Comments between the composer packages were causing the packages not to be installed.  The package `module-phpbrowser` is required by `bootstrap`.

comments removed and dependency added

---

cmfive.php

The CLI command `cmfive.php install core` now supports an optional CLI argument to specify which branch/tag/commit of cmfive-core to install.
Example:
`php cmfive.php install core hotfix/AdminConfigLogIssue`

support for default cli values

---

.build/environment/default/Dockerfile
.build/environment/default/configs/docker/Dockerfile.template
.build/environment/default/stage/fpm/php-fpm.conf
.build/environment/default/stage/fpm/php.ini
.build/environment/default/stage/nginx/default.conf
.build/environment/default/stage/nginx/nginx.conf
.build/environment/default/stage/start.sh
.build/environment/default/stage/supervisord.conf
.gitignore
docker-compose.yml

local run of 'staging' for default environment,
recreated and allowed for under !.gitignore
= restores ability to run docker-compose locally
without first installing any language support (no PHP nor PY)
refs:
issues:  missing functionality of 7.4 release
- [Y] I'm using the correct PHP Version (7.4! for current, 7.0 for legacy).
- [Y ] Tests are passing - manual observation of Docker-compose-up
- [na ] I've added comments to any new methods I've created or where else relevant.
- [ na] I've replaced magic method usage on DbService classes with the getInstance() static method.
default environment, recreated and allowed for under !.gitignore
refs:
issues: missing functionality of 7.4 release

fix: restore default docker build

---

.build/environment/test/config.yml
cmfiveTests.php

A non-zero exit status code wasn't been used when trying to run tests on a module that didn't exist. This was causing tests to appear as they had passed when none had actually run.
- Added exit status code when a module cannot be found.
- Added exit status code when $argc and $argv cannot be found.
- Updated test cmfive_core_ref to be master.

fix: missing module status code

---

test/Codeception/tests/boilerplate/acceptance/helpers/CmfiveSite.php

- [Y ] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [Y ] I've added comments to any new methods I've created or where else relevant.
- [? ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [? ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
refs:
issues:

fix: No Arrays To Codecept MouseOver WIP

---

test/Codeception/tests/boilerplate/acceptance/helpers/CmfiveSite.php

Co-authored-by: D.Crannaford <derek@2pisoftware.com>
- [Y ] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
- [Y ] I've added comments to any new methods I've created or where else relevant.
- [? ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [? ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
refs:
issues:

fix: No Arrays To Codecept MouseOver WIP (#52)

---

.build/environment/dev/configs/docker/Dockerfile.template
.build/environment/prod/configs/docker/Dockerfile.template
.build/environment/test/configs/docker/Dockerfile.template

Fixes the Ubuntu version used in Docker to an earlier version to ensure systemd is present as required by the version of PHP7.4 installed by the ondrej PPA
- Fix the Ubuntu version to Bionic 20220801 in the Docker templates
refs:
issues:
This change causes the [PR](https://github.com/2pisoftware/cmfive-core/pull/167) of a similar fix to pass.

fix: fixing ubuntu versions in docker

---

cmfive.php

fix:PHPversionComposerHint
[body footer?]
refs: [crm task numbers]
issues: [github issue numbers]
- [Y ] I'm using the correct PHP Version (7.4 for current, 7.2 for legacy).
Allow CI/CD to hint cmfive.php installer for Composer entry of PHP version
refs:
issues:

fix: PHP Version Composer Hint

---

cmfive.php

Correct typo in cmfive.php blocking ci/cd git action defaults

fix: Corrected isnull is_null typo

---

.codepipeline/local-dev/local-dev-config.php
.codepipeline/local-dev/start.sh
.github/workflows/ci.yml
.gitignore
README.md
cmfiveTests.php
docker-compose.yml
test/.install/install.sh
test/Codeception/tests/boilerplate/CmfiveUI.php
test/Codeception/tests/boilerplate/acceptance/helpers/CmfiveSite.php
test_agent-compose.yml

Immediate merge to promote stable ci test environment back to core

Feature: work to codeception5 (#66)

---

cmfive.php

cmfive.php to support explicit legacy 7.0 & 7.4 OR no version = 8.1 with named branch

fix: Stop core default as MASTER when no PHPversion

---

test/Codeception/tests/boilerplate/acceptance/helpers/CmfiveSite.php

- [Y ] I'm using the correct PHP Version (8.1 for current, 7.4 for legacy).
- [Y ] I've added comments to any new methods I've created or where else relevant.
- [n/a ] I've replaced magic method usage on DbService classes with the getInstance() static method.
- [n/a ] I've written any documentation for new features or where else relevant in the docs [repo](https://github.com/2pisoftware/cmfive-docs).
New designs now emerging on whole module at -->navigation level (not just specific actions)
So Codeception test must check if first step navbar click flipped over into BootStrap tpl before trying drop menu click-actions
Update Codeception nav-bar helper

Allow test nav helper to be re-entrant

---

.codepipeline/local-dev/configs/nginx/default.conf
.codepipeline/local-dev/configs/nginx/nginx.conf
.codepipeline/local-dev/local-dev-config.php
.codepipeline/local-dev/setup.sh
Dockerfile
README.md
config.php.example
docker-compose.yml
test/playwright/package.json

Adds HTTPS back, readme updates

fix/Https, Readme, Dev mode, Add override, Playwright fix

---

.codepipeline/test_agent/Dockerfile

Remove healthcheck on test container (.cmfive-installed)

---

Dockerfile
docker-compose.yml

Tweaks to make container healthchecks more reliable

Update healthcheck intervals and paths

---

.codepipeline/docker/setup.sh

Ensures that the symlink for system is set correctly when specifying a branch.

Improve branch env feature

---

CONTRIBUTING.md
README.md

Updated documentation for developing and depoying cmfive. https://github.com/2pisoftware/cmfive-boilerplate/blob/feat/md-update/README.md
fixes #126

Repo Documentation

---

test/playwright/docker_run.sh
test/playwright/playwright.config.ts

Allows running all the playwright tests through the official playwright docker image with a single command. Other method for running playwright are unaffected.

Add docker playwright script

---

.github/workflows/docker-image.yml

When pushing to master it will release a :latest cmfive image

fix: Enable master builds for docker images

---

.github/workflows/docker-image.yml

Related to #146 which enabled master builds but didnt tag as :latest.

fix: Add rule for latest tag

---

Dockerfile

This fixes missing node modules for the theme which was preventing being able to log in.

Fix missing node modules for theme

---

Dockerfile

Changes to master to be merged on to develop.

fix: Missing node modules for theme (#156) [DEVELOP]

---

.codepipeline/docker/setup.sh
Dockerfile
README.md
cmfive.php
test/Setup.txt

Closes #161.
This fix targets cmfive-boilerplate develop as cmfive-boilerplate master branch works, it just uses an older core.

fix: Core branch name

---

.github/workflows/docker-image.yml
Dockerfile

Adds a file to the docker image that contains more information about the built in core (commit hash, description and branch).
To get the metadata:
`docker exec -it cosine cat /.core-metadata`
The output can be sourced for another script if needed.

Add core metadata

---

.codepipeline/docker/config.default.php
.codepipeline/docker/setup.sh
README.md
docker-compose.yml
test/playwright/docker_run.sh
test/playwright/playwright.Dockerfile

Container strategy for node/ts Playwright test runner is challenged by access to also-containerised PHP DB helpers
Deprecate Container test runner affordance of 'npm/npx' DB helpers
Correctly scope DB helper tool calls vs local/container-re-entrant steps of test shell script
Add locale&TZ support to container setup

Feature: db strategy on docker tests

---

cmfive.php

Make sure global effort to require aws-sdk is always above known (Guzzle)CVE

fix: aws-sdk, Lift default lowest to safe version

---

test/playwright/cmfive.utils.ts
test/playwright/eslint.config.mjs
test/playwright/package-lock.json
test/playwright/package.json
test/playwright/test_boilerplate.ts

Modifies CmfiveHelper.fillAutocomplete to function on bootstrap5 sites with tom-select form fields.
Should be merged alongside 2pisoftware/cmfive-core#384 for tests to pass.
This is a draft PR that will be added to as I fix the tests in cmfive-core. It will be marked as ready to review once I've fixed all the tests.

bootstrap autocomplete test util
